name: pro_image_editor
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 7.6.4
homepage: https://github.com/hm21/pro_image_editor/
repository: https://github.com/hm21/pro_image_editor/
issue_tracker: https://github.com/hm21/pro_image_editor/issues/
documentation: https://github.com/hm21/pro_image_editor/
publish_to: none

topics:
  - image-editor
  - image
  - photo
  - picture
  - editor

screenshots:
  - description: "Showcase from the image editor with the frosted-glass design"
    path: assets/showcase-frosted-glass.jpg
  - description: "Showcase from the image editor with the Whatsapp design"
    path: assets/showcase-whatsapp.jpg
  - description: "Showcase from the image editor with simple design"
    path: assets/showcase.jpg

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  emoji_picker_flutter:
    git: https://github.com/kumsumit/emoji_picker_flutter.git
  http: ^1.2.2
  image: ^4.5.2
  intl: ^0.19.0
  vibration: 
    git: https://github.com/kumsumit/vibration.git
  mime: ^2.0.0
  share_plus:
    git: https://github.com/kumsumit/share_plus.git
  web: ^1.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  mockito: ^5.4.5
  network_image_mock: ^2.0.0

flutter:
  assets:
    - lib/web/web_worker.dart.js
    - lib/web/web_worker.dart.js.map
    - lib/web/web_worker.dart.wasm
  fonts:
   - family: ProImageEditorIcons
     fonts:
      - asset: assets/fonts/ProImageEditorIcons.ttf